### ISSUE TITLE
Curl error on Windows

### ISSUE THREAD

**Issue by alanfzf** [Jezda1337/cmp_bootstrap#1]
Seems like the flag "compressed" used on the curl request is not supported on windows

![image](https://github.com/Jezda1337/cmp_bootstrap/assets/29936954/ee4adb8f-286c-4b51-8fec-cd46eea64919)

**Comment by Jezda1337** [comment]
What curl version do you have installed? 

by the docs curl --compressed is supported on windows machines

**Comment by alanfvn** [comment]
I’m using the bundled curl that comes with Neovim installation so I’m not really sure which version it is

**Comment by Jezda1337** [comment]
@alanfvn 
neovim doesn't have curl by it self, it have curl wrapper, but still relay on installed curl on ur system. [Here](https://github.com/nvim-lua/plenary.nvim/blob/499e0743cf5e8075cd32af68baa3946a1c76adf1/lua/plenary/curl.lua#L255).
Try to install curl on ur system and add to the path.
And if that doesn't work pls post error message.

**Comment by alanfzf** [comment]
Thank you @Jezda1337, my bad,  it seems like the curl version bundled with windows, doesn't support the --compressed flag
![Screenshot 2023-06-08 113609](https://github.com/Jezda1337/cmp_bootstrap/assets/29936954/6fbd91da-5fab-4bc2-8321-ce3778cd6b88)



however as Git comes with a MinGW installation, i added that curl to the path
![Screenshot 2023-06-08 114441](https://github.com/Jezda1337/cmp_bootstrap/assets/29936954/5229f48c-8960-4740-81b5-1d4807e94f05)
![Screenshot 2023-06-08 114359](https://github.com/Jezda1337/cmp_bootstrap/assets/29936954/7ae05255-38c3-46f3-927c-a9d82b71e314)

now it seems like there's no more errors on my end 👍
![Screenshot 2023-06-08 114255](https://github.com/Jezda1337/cmp_bootstrap/assets/29936954/91393153-51bb-4124-9750-e080fcd089a3)


Closing the issue
